// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface AboutSection {
  id: string;
  slug: string | null;
  status: string;
  label: string;
  subtitle: string;
  paragraphs: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Certificate {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  certificate_url: string;
  issuer: string;
  issuer_id: string;
  issuer_website: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Profile {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  label: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Project {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: PortableTextBlock[];
  url?: string;
  start_date: string;
  end_date?: string;
  labels: unknown;
  image: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SocialLink {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  label: string;
  url: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    about: AboutSection;
    certificates: Certificate;
    profile: Profile;
    projects: Project;
    socials: SocialLink;
  }
}